#!/usr/bin/env bash

set -e

ARGS=$@

if egrep -q integration <(echo "$ARGS"); then
   (cd ../../..; ./scripts/remote-fly ci/nested-shed-tests.yml -- -nodes 4 $ARGS)
elif [ -d $ARGS ] &&
     [ "$(find $ARGS -maxdepth 1 -name '*_linux_test.go')" != "" ]; then
   (cd ../../..; ./scripts/remote-fly ci/nested-shed-tests.yml -- $ARGS)
else
  ginkgo -p -race -nodes=8 -failOnPending -randomizeSuites $ARGS
fi

