// This file was generated by counterfeiter
package repository_fetcherfakes

import (
	"net/url"
	"sync"

	"code.cloudfoundry.org/garden-shed/layercake"
	"code.cloudfoundry.org/garden-shed/repository_fetcher"
	"code.cloudfoundry.org/lager"
)

type FakeRemoteImageIDFetcher struct {
	FetchIDStub        func(log lager.Logger, u *url.URL) (layercake.ID, error)
	fetchIDMutex       sync.RWMutex
	fetchIDArgsForCall []struct {
		log lager.Logger
		u   *url.URL
	}
	fetchIDReturns struct {
		result1 layercake.ID
		result2 error
	}
	fetchIDReturnsOnCall map[int]struct {
		result1 layercake.ID
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRemoteImageIDFetcher) FetchID(log lager.Logger, u *url.URL) (layercake.ID, error) {
	fake.fetchIDMutex.Lock()
	ret, specificReturn := fake.fetchIDReturnsOnCall[len(fake.fetchIDArgsForCall)]
	fake.fetchIDArgsForCall = append(fake.fetchIDArgsForCall, struct {
		log lager.Logger
		u   *url.URL
	}{log, u})
	fake.recordInvocation("FetchID", []interface{}{log, u})
	fake.fetchIDMutex.Unlock()
	if fake.FetchIDStub != nil {
		return fake.FetchIDStub(log, u)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.fetchIDReturns.result1, fake.fetchIDReturns.result2
}

func (fake *FakeRemoteImageIDFetcher) FetchIDCallCount() int {
	fake.fetchIDMutex.RLock()
	defer fake.fetchIDMutex.RUnlock()
	return len(fake.fetchIDArgsForCall)
}

func (fake *FakeRemoteImageIDFetcher) FetchIDArgsForCall(i int) (lager.Logger, *url.URL) {
	fake.fetchIDMutex.RLock()
	defer fake.fetchIDMutex.RUnlock()
	return fake.fetchIDArgsForCall[i].log, fake.fetchIDArgsForCall[i].u
}

func (fake *FakeRemoteImageIDFetcher) FetchIDReturns(result1 layercake.ID, result2 error) {
	fake.FetchIDStub = nil
	fake.fetchIDReturns = struct {
		result1 layercake.ID
		result2 error
	}{result1, result2}
}

func (fake *FakeRemoteImageIDFetcher) FetchIDReturnsOnCall(i int, result1 layercake.ID, result2 error) {
	fake.FetchIDStub = nil
	if fake.fetchIDReturnsOnCall == nil {
		fake.fetchIDReturnsOnCall = make(map[int]struct {
			result1 layercake.ID
			result2 error
		})
	}
	fake.fetchIDReturnsOnCall[i] = struct {
		result1 layercake.ID
		result2 error
	}{result1, result2}
}

func (fake *FakeRemoteImageIDFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchIDMutex.RLock()
	defer fake.fetchIDMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeRemoteImageIDFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository_fetcher.RemoteImageIDFetcher = new(FakeRemoteImageIDFetcher)
