// This file was generated by counterfeiter
package fake_id_provider

import (
	"sync"

	"code.cloudfoundry.org/garden-shed/layercake"
)

type FakeIDProvider struct {
	ProvideIDStub        func(path string) (layercake.ID, error)
	provideIDMutex       sync.RWMutex
	provideIDArgsForCall []struct {
		path string
	}
	provideIDReturns struct {
		result1 layercake.ID
		result2 error
	}
	provideIDReturnsOnCall map[int]struct {
		result1 layercake.ID
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIDProvider) ProvideID(path string) (layercake.ID, error) {
	fake.provideIDMutex.Lock()
	ret, specificReturn := fake.provideIDReturnsOnCall[len(fake.provideIDArgsForCall)]
	fake.provideIDArgsForCall = append(fake.provideIDArgsForCall, struct {
		path string
	}{path})
	fake.recordInvocation("ProvideID", []interface{}{path})
	fake.provideIDMutex.Unlock()
	if fake.ProvideIDStub != nil {
		return fake.ProvideIDStub(path)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.provideIDReturns.result1, fake.provideIDReturns.result2
}

func (fake *FakeIDProvider) ProvideIDCallCount() int {
	fake.provideIDMutex.RLock()
	defer fake.provideIDMutex.RUnlock()
	return len(fake.provideIDArgsForCall)
}

func (fake *FakeIDProvider) ProvideIDArgsForCall(i int) string {
	fake.provideIDMutex.RLock()
	defer fake.provideIDMutex.RUnlock()
	return fake.provideIDArgsForCall[i].path
}

func (fake *FakeIDProvider) ProvideIDReturns(result1 layercake.ID, result2 error) {
	fake.ProvideIDStub = nil
	fake.provideIDReturns = struct {
		result1 layercake.ID
		result2 error
	}{result1, result2}
}

func (fake *FakeIDProvider) ProvideIDReturnsOnCall(i int, result1 layercake.ID, result2 error) {
	fake.ProvideIDStub = nil
	if fake.provideIDReturnsOnCall == nil {
		fake.provideIDReturnsOnCall = make(map[int]struct {
			result1 layercake.ID
			result2 error
		})
	}
	fake.provideIDReturnsOnCall[i] = struct {
		result1 layercake.ID
		result2 error
	}{result1, result2}
}

func (fake *FakeIDProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.provideIDMutex.RLock()
	defer fake.provideIDMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeIDProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ layercake.IDProvider = new(FakeIDProvider)
